### ISSUE TITLE
Add Cell bender publication to publications page

### ISSUE THREAD

**Issue by nrockweiler** [broadinstitute/chbv#20]
https://www.nature.com/articles/s41592-023-01943-7

**Comment by nrockweiler** [comment]
Maybe add a little news snippet about it?

**Comment by aaron-6960** [comment]
The issue is not clear. Currently there are only 3 rows of data in publications, should we add a new row
Also which file to edit (first time doing this and not so familiar sorry for the inconvenience : ) )

**Comment by nrockweiler** [comment]
Hi @aaron-6960 -- can you tell me who you are?
