### ISSUE TITLE
Team Page Updates

### ISSUE THREAD

**Issue by kikuichihara** [broadinstitute/chbv#45]
-remove Paola Arlotta as a co-investigator (she is no longer working on the project)
-move Aleks Goeva to alumni
-move Jonah Langlieb to alumni (after 6/30/24)
-move CJ Crombie to alumni (after 6/30/24)
-add Matthew Karikomi to Computational Analysis (postdoc in Welch lab, mkarikom@med.umich.edu)
-add Julianna Milidantri to Data Generation (RAI starting on 6/3)

**Comment by nrockweiler** [comment]
Emailed Julianna, Matthew, and Jonah for more info on 6/3.
